stages:
  - mirror

mirror_to_github:
  stage: mirror
  tags:
    - sunland
  script:
    - |
      # Check if git-lfs is installed
      if (!(Get-Command git-lfs -ErrorAction SilentlyContinue)) {
        Write-Host "git-lfs is not installed. Attempting installation..."

        # Download git-lfs (replace with the latest download URL)
        $lfsDownloadUrl = "https://github.com/git-lfs/git-lfs/releases/latest/download/git-lfs-windows-amd64.zip"
        $lfsZipFile = "$env:TEMP\git-lfs.zip"
        $lfsExtractPath = "$env:ProgramFiles\Git LFS"

        Invoke-WebRequest -Uri $lfsDownloadUrl -OutFile $lfsZipFile
        Expand-Archive -Path $lfsZipFile -DestinationPath $lfsExtractPath -Force

        # Add git-lfs to PATH
        $env:Path += ";$lfsExtractPath"
        [Environment]::SetEnvironmentVariable("Path", $env:Path, "User")

        # Verify installation
        git-lfs --version
      } else {
        Write-Host "git-lfs is already installed."
      }

      git lfs install

      $GITHUB_API_URL = "https://api.github.com/repos/$env:GITHUB_REPO"
      $GITHUB_AUTH_HEADER = "Authorization: token $env:GITHUB_TOKEN"
      $GITHUB_REPO_EXISTS = $(curl -s -o /dev/null -w '%{http_code}' -H "$GITHUB_AUTH_HEADER" "$GITHUB_API_URL")

      if ($GITHUB_REPO_EXISTS -eq 404) {
        Write-Host "GitHub repository does not exist. Creating..."
        curl -X POST -H "$GITHUB_AUTH_HEADER" -d '{"name":"$(Split-Path -Leaf $env:GITHUB_REPO)"}' "https://api.github.com/user/repos"
      } else {
        Write-Host "GitHub repository exists. Updating..."
      }

      git remote add github "https://oauth2:$env:GITHUB_TOKEN@github.com/$env:GITHUB_REPO.git"
      git fetch --all
      git lfs fetch --all
      git push --mirror github
      git lfs push --mirror github
  only:
    - branches
    - tags