stages:
  - mirror

mirror_to_github:
  stage: mirror
  tags:
    - sunland
  script:
    - |
      # Debugging
      echo "Mirroring to GitHub..."
      echo "Current branch: $(git branch --show-current)"
      git --version
      git-lfs --version
      echo "Path: $env:PATH"

      # Add remote if it doesn't exist
      if [[ -z $(git remote get-url github) ]]; then
        git remote add github "https://oauth2:$GITHUB_TOKEN@github.com/devopsyuvan123/gitlab-mirroring-test-github.git"
        echo "Remote added"
      else
        echo "Remote already exists"
      fi

      # Fetch the remote main branch
      git fetch github main

      # Check if the local main branch is up to date with the remote
      if [[ $(git rev-parse origin/main) == $(git rev-parse github/main) ]]; then
        echo "Local main branch is up to date."
      else
          # Force push to GitHub
          git push github origin/main:refs/heads/main --force
          if [ $? -eq 0 ]; then
            echo "Mirroring successful"
          else
            echo "Mirroring failed"
            exit 1
          fi
      fi

      # Git LFS push (if applicable)
      if command -v git-lfs &> /dev/null; then
        echo "Pushing Git LFS objects..."
        git lfs push --all github
      fi
  only:
    - main