stages:
  - mirror

mirror_to_github:
  stage: mirror
  tags:
    - sunland
  script:
    - |
      # Debugging
      echo "Mirroring to GitHub..."
      echo "Current branch: $(git branch --show-current)"
      git --version
      git-lfs --version
      echo "Path: $env:PATH"

      # Initialize git repository.
      if (!(Test-Path ".git")) {
        git init
      }

      # Add remote if it doesn't exist
      if (-not (git remote get-url github)) {
        git remote add github "https://oauth2:$GITHUB_TOKEN@github.com/devopsyuvan123/test-repo-for-mirroring"
        echo "Remote added"
      } else {
        echo "Remote already exists"
      }

      # Fetch the remote main branch
      git fetch github main

      # Check if the local main branch is up to date with the remote
      if ((git rev-parse origin/main) -eq (git rev-parse github/main)) {
        echo "Local main branch is up to date."
      } else {
        # Force push to GitHub
        git push github origin/main:refs/heads/main --force
        if ($LASTEXITCODE -eq 0) {
          echo "Mirroring successful"
        } else {
          echo "Mirroring failed"
          exit 1
        }
      }

      # Git LFS push (if applicable)
      if (Get-Command git-lfs -ErrorAction SilentlyContinue) {
        echo "Pushing Git LFS objects..."
        git lfs push --all github
        if ($LASTEXITCODE -ne 0) {
          echo "Git LFS push failed"
          exit 1
        }
      }
  only:
    - main