stages:
  - mirror

mirror_to_github:
  stage: mirror
  tags:
    - sunland
  script:
    - |
      # ... (Git LFS installation) ...

      git lfs install

      $GITHUB_API_URL = "https://api.github.com/repos/$env:GITHUB_REPO"
      $GITHUB_AUTH_HEADER = @{ "Authorization" = "token $env:GITHUB_TOKEN" }

      Write-Host "Authorization Header: $($GITHUB_AUTH_HEADER.Authorization)" # Print the header

      try {
          # ... (Repository existence check) ...
      } catch {
          # ... (Error handling) ...
      }

      if ($GITHUB_REPO_EXISTS -eq 404) {
        Write-Host "GitHub repository does not exist. Creating..."
        $Body = @{ "name" = "$(Split-Path -Leaf $env:GITHUB_REPO)" } | ConvertTo-Json
        Invoke-WebRequest -Uri "https://api.github.com/user/repos" -Headers $GITHUB_AUTH_HEADER -Method Post -Body $Body -ContentType "application/json" -ErrorAction Stop
      } else {
        Write-Host "GitHub repository exists. Updating..."
      }

      # ... (Git mirroring) ...
  only:
    - branches
    - tags