stages:
  - mirror

mirror_to_github:
  stage: mirror
  tags:
    - sunland
  script:
    - echo "Mirroring to GitHub..."
    - echo "Current branch: $(git branch --show-current)"
    - git --version
    - git-lfs --version

    # Configure Git
    - git config --global user.email "yuvanshankars@vyapisoft.com"
    - git config --global user.name "YuvanShankarS"

    # Ensure the repo is initialized
    - if [ ! -d ".git" ]; then git init; fi

    # Add the GitHub remote if it doesn't exist
    - if ! git remote | grep -q "github"; then
        git remote add github "https://oauth2:${GITHUB_TOKEN}@github.com/devopsyuvan123/test-repo-for-mirroring.git";
      fi

    # Fetch the latest from GitHub
    - git fetch github main || true

    # Push changes from GitLab to GitHub
    - git push --mirror "https://oauth2:${GITHUB_TOKEN}@github.com/devopsyuvan123/test-repo-for-mirroring.git"

    # Push Git LFS objects (if applicable)
    - git lfs push --all github || true
  only:
    - main
