stages:
  - mirror

mirror_to_github:
  stage: mirror
  tags:
    - sunland
  script:
    - |
      # Install git-lfs within the alpine/git image
      docker run --rm -v "$(pwd):/repo" alpine/git:latest sh -c "apk update && apk add git-lfs && cd /repo && git lfs install"

      $GITHUB_API_URL = "https://api.github.com/repos/$env:GITHUB_REPO"
      $GITHUB_AUTH_HEADER = "Authorization: token $env:GITHUB_TOKEN"
      $GITHUB_REPO_EXISTS = $(curl -s -o /dev/null -w '%{http_code}' -H "$GITHUB_AUTH_HEADER" "$GITHUB_API_URL")

      if ($GITHUB_REPO_EXISTS -eq 404) {
        Write-Host "GitHub repository does not exist. Creating..."
        curl -X POST -H "$GITHUB_AUTH_HEADER" -d '{"name":"$(Split-Path -Leaf $env:GITHUB_REPO)"}' "https://api.github.com/user/repos"
      } else {
        Write-Host "GitHub repository exists. Updating..."
      }

      git remote add github "https://oauth2:$env:GITHUB_TOKEN@github.com/$env:GITHUB_REPO.git"
      git fetch --all
      git lfs fetch --all
      git push --mirror github
      git lfs push --mirror github
  only:
    - branches
    - tags